# Trabalho Final

**Aluno**:

**Matrícula**:



## 05 - Tratamento da base *experiencia_trabalho.csv*

Descreva a base com suas palavras.

In [141]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

experiencia = pd.read_csv("bases/experiencia_trabalho.csv")

# Análise inicial
print("Nº de registros:", len(experiencia))
print("Nº de valores únicos de perfil_id:", experiencia.perfil_id.nunique())
print("Nº de valores únicos de company:", experiencia.company.nunique())
print("Nº de valores únicos de location:", experiencia.location.nunique())
print("Nº de valores únicos de position:", experiencia.position.nunique())
print("Nº de valores vazios de company:", experiencia.company.isnull().sum())
print("Nº de valores vazios de date:", experiencia.date.isnull().sum())
print("Nº de valores vazios de location:", experiencia.location.isnull().sum())
print("Nº de valores vazios de position:", experiencia.position.isnull().sum())

experiencia.describe(include="all")

Nº de registros: 497
Nº de valores únicos de perfil_id: 111
Nº de valores únicos de company: 2
Nº de valores únicos de location: 71
Nº de valores únicos de position: 386
Nº de valores vazios de company: 25
Nº de valores vazios de date: 26
Nº de valores vazios de location: 160
Nº de valores vazios de position: 25

,company,date,location,position,perfil_id
count,472,471,337,472,497.000000
unique,2,328,71,386,NaN
top,Any Company,mar de 2017 – o momento,"Belo Horizonte e Região, Brasil",Software Developer,NaN
freq,318,21,138,9,NaN
mean,NaN,NaN,NaN,NaN,54.187123
std,NaN,NaN,NaN,NaN,32.199717
min,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,27.000000
50%,NaN,NaN,NaN,NaN,54.000000
75%,NaN,NaN,NaN,NaN,81.000000
max,NaN,NaN,NaN,NaN,110.000000

In [142]:
experiencia = experiencia[(experiencia.company.notnull()) & (experiencia.position.notnull()) & (experiencia.date.notnull())]
print("Nº de valores únicos de perfil_id:", experiencia.perfil_id.nunique())
print("Nº de registros restantes após remoção dos vazios:", len(experiencia))
print("Nº de valores vazios de company:", experiencia.company.isnull().sum())
print("Nº de valores vazios de date:", experiencia.date.isnull().sum())
print("Nº de valores vazios de location:", experiencia.location.isnull().sum())
print("Nº de valores vazios de position:", experiencia.position.isnull().sum())

Nº de valores únicos de perfil_id: 110
Nº de registros restantes após remoção dos vazios: 471
Nº de valores vazios de company: 0
Nº de valores vazios de date: 0
Nº de valores vazios de location: 134
Nº de valores vazios de position: 0

## 05.1 - Tratamento das data

A coluna **date** pode ser quebrada no ano de início (**inicio**) e no ano de fim (**fim**) da experiência. As experiências em aberto, possuem o texto "o momento" que será interpretado como o mês/ano da extração dos dados (09/2017). As experiências em aberto serão marcadas na coluna booleana **atual**, que indicando que o funcionário ainda trabalha na trojan.

In [143]:
experiencia.date = experiencia.date.str.replace('o momento','set de 2017')

ini_fim = experiencia.date.str.split('–')

experiencia['mesano_ini'] = ini_fim.str.get(0).str.strip()
experiencia['mesano_fim'] = ini_fim.str.get(1).str.strip()

experiencia['atual'] = (experiencia.mesano_fim.str.contains('set de 2017'))
experiencia['ano_ini'] = experiencia.mesano_ini.str.extract('(\d+)')
experiencia['ano_fim'] = experiencia.mesano_fim.str.extract('(\d+)')

A informação de duração da experiência (**duracao**) é derivada calculando a diferença do fim ao início em meses.

In [148]:
# calcula a duração estimada de cada experiência em meses

experiencia.mesano_ini = experiencia.mesano_ini.str.replace('jan','01') \
                        .str.replace('fev','02') \
                        .str.replace('mar','03') \
                        .str.replace('abr','04') \
                        .str.replace('mai','05') \
                        .str.replace('jun','06') \
                        .str.replace('jul','07') \
                        .str.replace('ago','08') \
                        .str.replace('set','09') \
                        .str.replace('out','10') \
                        .str.replace('nov','11') \
                        .str.replace('dez','12')

experiencia.mesano_fim = experiencia.mesano_fim.str.replace('jan','01') \
                        .str.replace('fev','02') \
                        .str.replace('mar','03') \
                        .str.replace('abr','04') \
                        .str.replace('mai','05') \
                        .str.replace('jun','06') \
                        .str.replace('jul','07') \
                        .str.replace('ago','08') \
                        .str.replace('set','09') \
                        .str.replace('out','10') \
                        .str.replace('nov','11') \
                        .str.replace('dez','12')

experiencia.loc[(experiencia.mesano_ini.str.len() == 4), 'mesano_ini'] = '01 de '+experiencia.mesano_ini
experiencia.loc[(experiencia.mesano_fim.str.len() == 4), 'mesano_fim'] = '01 de '+experiencia.mesano_fim 

experiencia['mesano_ini_d'] = pd.to_datetime(experiencia.mesano_ini, format='%m de %Y')
experiencia['mesano_fim_d'] = pd.to_datetime(experiencia.mesano_fim, format='%m de %Y')

experiencia['duracao'] = experiencia.mesano_fim_d.dt.to_period('M') - experiencia.mesano_ini_d.dt.to_period('M')

Algumas informações consolidadas por funcionários podem ser extraídas dessa base. É possível extrair o tempo de carreira na empresa em meses (**tempo_empresa_meses**), o tempo de carreira no mercado em geral em meses (**tempo_mercado_meses**), e também a quantidade de empregos que o funcionário já teve (**qtd_empregos**), o que pode auxiliar em algo na análise. Portanto, obtenha essas informações.

In [197]:
tempo_empresa_meses = experiencia[(experiencia.atual) & (experiencia.company == 'Trojan Technologies')].groupby(['perfil_id']).duracao.max().to_frame()
tempo_mercado_meses = experiencia.groupby(['perfil_id']).duracao.sum().to_frame()
qtd_empregos = experiencia.groupby(['perfil_id']).position.count().to_frame()

#experiencia[(experiencia.atual) & (experiencia.company == 'Trojan Technologies') & ((experiencia.perfil_id == 6) | (experiencia.perfil_id == 11) | (experiencia.perfil_id == 12))]

## 05.2 - Cargo atual na empresa

In [60]:
cargo_atual = experiencia[(experiencia.atual) & (experiencia.company == 'Trojan Technologies')]

## 05.3 - Setor do Funcionário na empresa

A partir da posicao dos funcionários, é possível descobrir (ou inferir) o setor que eles trabalham.

In [61]:
cargo_atual

,company,date,location,position,perfil_id,mesano_ini,mesano_fim,atual,ano_ini,ano_fim
0,Trojan Technologies,set de 2011 – set de 2017,"Belo Horizonte e Região, Brasil",CEO and Founder,0,set de 2011,set de 2017,True,2011,2017
10,Trojan Technologies,jul de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Product Manager,1,jul de 2017,set de 2017,True,2017,2017
16,Trojan Technologies,nov de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Full Stack Developer,2,nov de 2016,set de 2017,True,2016,2017
20,Trojan Technologies,ago de 2017 – set de 2017,NaN,CRM Analyst,3,ago de 2017,set de 2017,True,2017,2017
24,Trojan Technologies,mar de 2017 – set de 2017,NaN,Sales Operations Coordinator,4,mar de 2017,set de 2017,True,2017,2017
29,Trojan Technologies,jul de 2016 – set de 2017,NaN,Key Account Manager,5,jul de 2016,set de 2017,True,2016,2017
34,Trojan Technologies,nov de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Software Engineer and Data Scientist,6,nov de 2016,set de 2017,True,2016,2017
35,Trojan Technologies,nov de 2016 – set de 2017,"Belo Horizonte Area, Brazil",Data Engineer,6,nov de 2016,set de 2017,True,2016,2017
39,Trojan Technologies,abr de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Aprediz administrativo,7,abr de 2017,set de 2017,True,2017,2017
41,Trojan Technologies,jan de 2011 – set de 2017,"Belo Horizonte e Região, Brasil",Founder and CFO,8,jan de 2011,set de 2017,True,2011,2017
46,Trojan Technologies,ago de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Sales Operations Manager,9,ago de 2016,set de 2017,True,2016,2017
49,Trojan Technologies,mai de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Head of In-Store Operation,10,mai de 2017,set de 2017,True,2017,2017
54,Trojan Technologies,set de 2017 – set de 2017,NaN,People Consultant,11,set de 2017,set de 2017,True,2017,2017
55,Trojan Technologies,jul de 2016 – set de 2017,NaN,Key Account Manager,11,jul de 2016,set de 2017,True,2016,2017
59,Trojan Technologies,set de 2017 – set de 2017,Belo Horizonte,Operações ERP,12,set de 2017,set de 2017,True,2017,2017
60,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Time de Expansão,12,mar de 2017,set de 2017,True,2017,2017
64,Trojan Technologies,ago de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Estagiária de CRM,13,ago de 2017,set de 2017,True,2017,2017
69,Trojan Technologies,mai de 2017 – set de 2017,"Belo Horizonte Area, Brazil",Product Manager,14,mai de 2017,set de 2017,True,2017,2017
74,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Key Account,15,mar de 2017,set de 2017,True,2017,2017
79,Trojan Technologies,set de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Head of People,16,set de 2017,set de 2017,True,2017,2017
84,Trojan Technologies,ago de 2017 – set de 2017,"Belo Horizonte Area, Brazil",Public Relations Intern,17,ago de 2017,set de 2017,True,2017,2017
85,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte Area, Brazil",Customer Success Intern,17,mar de 2017,set de 2017,True,2017,2017
87,Trojan Technologies,jul de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Trade Marketing Analyst,18,jul de 2017,set de 2017,True,2017,2017
92,Trojan Technologies,mar de 2017 – set de 2017,Belo Horizonte,Customer Success - Intern,19,mar de 2017,set de 2017,True,2017,2017
95,Trojan Technologies,jan de 2017 – set de 2017,NaN,Time de Expansão,20,jan de 2017,set de 2017,True,2017,2017
98,Trojan Technologies,fev de 2017 – set de 2017,NaN,Onboarding Coordinator,21,fev de 2017,set de 2017,True,2017,2017
103,Trojan Technologies,out de 2016 – set de 2017,NaN,Analista de DP,22,out de 2016,set de 2017,True,2016,2017
108,Trojan Technologies,jan de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Diretora de arte,23,jan de 2017,set de 2017,True,2017,2017
111,Trojan Technologies,ago de 2016 – set de 2017,Belo Horizonte,Engenheiro de Software,24,ago de 2016,set de 2017,True,2016,2017
114,Trojan Technologies,jan de 2017 – set de 2017,NaN,Costomer Success,25,jan de 2017,set de 2017,True,2017,2017
120,Trojan Technologies,fev de 2017 – set de 2017,"Belo Horizonte, Minas Gerais",Customer Sucess Analyst,26,fev de 2017,set de 2017,True,2017,2017
122,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Estagiária de Customer Success,27,mar de 2017,set de 2017,True,2017,2017
127,Trojan Technologies,mai de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Coordenadora de Branding,28,mai de 2017,set de 2017,True,2017,2017
132,Trojan Technologies,out de 2016 – set de 2017,"Manaus e Região, Brasil",Lead Software Developer,29,out de 2016,set de 2017,True,2016,2017
137,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Customer Success,30,mar de 2017,set de 2017,True,2017,2017
138,Trojan Technologies,jul de 2016 – set de 2017,"Belo Horizonte Area, Brazil",Full Stack Engineer,31,jul de 2016,set de 2017,True,2016,2017
142,Trojan Technologies,jul de 2017 – set de 2017,"Belo Horizonte, Minas Gerais",Key Account Manager,32,jul de 2017,set de 2017,True,2017,2017
143,Trojan Technologies,fev de 2017 – set de 2017,"Belo Horizonte, Minas Gerais",Business Sales Executive,32,fev de 2017,set de 2017,True,2017,2017
148,Trojan Technologies,out de 2013 – set de 2017,"Belo Horizonte Area, Brazil","Lead Product Designer, Partner",33,out de 2013,set de 2017,True,2013,2017
153,Trojan Technologies,jul de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Product Manager,34,jul de 2016,set de 2017,True,2016,2017
158,Trojan Technologies,dez de 2012 – set de 2017,"Belo Horizonte e Região, Brasil",Engenheiro de software sênior,35,dez de 2012,set de 2017,True,2012,2017
164,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte, Minas Gerais, Brésil",Customer Success,36,mar de 2017,set de 2017,True,2017,2017
167,Trojan Technologies,jan de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Software Developer,37,jan de 2016,set de 2017,True,2016,2017
173,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Arquiteto de soluções,38,mar de 2017,set de 2017,True,2017,2017
174,Trojan Technologies,abr de 2015 – set de 2017,"Belo Horizonte e Região, Brasil",Engenheiro de Software,38,abr de 2015,set de 2017,True,2015,2017
177,Trojan Technologies,out de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Business Intelligence and Data Analyst,39,out de 2016,set de 2017,True,2016,2017
182,Trojan Technologies,mar de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Tech Leader,40,mar de 2016,set de 2017,True,2016,2017
187,Trojan Technologies,jan de 2017 – set de 2017,"Belo Horizonte, Minas Gerais",Analista financeiro,41,jan de 2017,set de 2017,True,2017,2017
188,Trojan Technologies,nov de 2015 – set de 2017,"Belo Horizonte e Região, Brasil",Estagiária de finanças,41,nov de 2015,set de 2017,True,2015,2017
192,Trojan Technologies,jul de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Analista financeiro,42,jul de 2017,set de 2017,True,2017,2017
195,Trojan Technologies,out de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Analista de controladoria,43,out de 2016,set de 2017,True,2016,2017
197,Trojan Technologies,ago de 2017 – set de 2017,"Belo Horizonte Area, Brazil",Software Architect,44,ago de 2017,set de 2017,True,2017,2017
202,Trojan Technologies,mai de 2017 – set de 2017,"Manaus e Região, Brasil",Desenvolvedor Júnior,45,mai de 2017,set de 2017,True,2017,2017
206,Trojan Technologies,out de 2016 – set de 2017,"Belo Horizonte Area, Brazil",Software Developer,46,out de 2016,set de 2017,True,2016,2017
207,Trojan Technologies,out de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Talent Acquisition,47,out de 2016,set de 2017,True,2016,2017
211,Trojan Technologies,jan de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Gestora do time de Pessoas - Responsável por R...,48,jan de 2017,set de 2017,True,2017,2017
217,Trojan Technologies,mar de 2015 – set de 2017,"Belo Horizonte Area, Brazil",Senior UX Designer,49,mar de 2015,set de 2017,True,2015,2017
222,Trojan Technologies,jan de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Director of Marketing,50,jan de 2017,set de 2017,True,2017,2017
227,Trojan Technologies,mar de 2015 – set de 2017,"Belo Horizonte e Região, Brasil",COO,51,mar de 2015,set de 2017,True,2015,2017
236,Trojan Technologies,jul de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Product Growth Manager,52,jul de 2017,set de 2017,True,2017,2017
244,Trojan Technologies,jan de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Creative Designer,53,jan de 2017,set de 2017,True,2017,2017
247,Trojan Technologies,abr de 2014 – set de 2017,"Belo Horizonte e Região, Brasil",Head of Customer Success,54,abr de 2014,set de 2017,True,2014,2017
253,Trojan Technologies,ago de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Purchasing Analyst,55,ago de 2017,set de 2017,True,2017,2017
258,Trojan Technologies,dez de 2016 – set de 2017,NaN,Estágio em Marketing CRM,56,dez de 2016,set de 2017,True,2016,2017
261,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Coordenadora de CS,57,mar de 2017,set de 2017,True,2017,2017
266,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Analista de DP,58,mar de 2017,set de 2017,True,2017,2017
270,Trojan Technologies,dez de 2016 – set de 2017,NaN,Estagiaria do Financeiro,59,dez de 2016,set de 2017,True,2016,2017
275,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte Area, Brazil",Head of Data Analytics,60,mar de 2017,set de 2017,True,2017,2017
280,Trojan Technologies,ago de 2016 – set de 2017,"Belo Horizonte Area, Brazil",Commercial Analyst,61,ago de 2016,set de 2017,True,2016,2017
284,Trojan Technologies,jun de 2017 – set de 2017,"Belo Horizonte Area, Brazil",Head Of Commercial,62,jun de 2017,set de 2017,True,2017,2017
289,Trojan Technologies,ago de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Analista de tecnologia da informação,63,ago de 2017,set de 2017,True,2017,2017
294,Trojan Technologies,mar de 2015 – set de 2017,"Belo Horizonte e Região, Brasil",Analista Financeiro,64,mar de 2015,set de 2017,True,2015,2017
299,Trojan Technologies,2017 – set de 2017,"Belo Horizonte Area, Brazil",People Consultant,65,2017,set de 2017,True,2017,2017
300,Trojan Technologies,nov de 2014 – set de 2017,"Belo Horizonte e Região, Brasil",Programador Front end,65,nov de 2014,set de 2017,True,2014,2017
302,Trojan Technologies,nov de 2016 – set de 2017,"Belo Horizonte, Minas Gerais",Business Development Manager,66,nov de 2016,set de 2017,True,2016,2017
307,Trojan Technologies,out de 2014 – set de 2017,NaN,Customer Success,67,out de 2014,set de 2017,True,2014,2017
309,Trojan Technologies,nov de 2015 – set de 2017,"Belo Horizonte, Minas Gerais, Brazil",Head of Trojan Technologies In-Store,68,nov de 2015,set de 2017,True,2015,2017
314,Trojan Technologies,jul de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Trade Marketing,69,jul de 2016,set de 2017,True,2016,2017
319,Trojan Technologies,jul de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Sales Operations Analyst,70,jul de 2017,set de 2017,True,2017,2017
324,Trojan Technologies,nov de 2016 – set de 2017,NaN,Estagiária de marketing,71,nov de 2016,set de 2017,True,2016,2017
328,Trojan Technologies,ago de 2015 – set de 2017,"Belo Horizonte e Região, Brasil",Coordenador de marketing,72,ago de 2015,set de 2017,True,2015,2017
334,Trojan Technologies,out de 2016 – set de 2017,NaN,Android Developer,73,out de 2016,set de 2017,True,2016,2017
335,Trojan Technologies,mar de 2017 – set de 2017,"São Paulo Area, Brazil",Commercial,74,mar de 2017,set de 2017,True,2017,2017
343,Trojan Technologies,fev de 2017 – set de 2017,"Varginha e Região, Brasil",Gerente de operações,75,fev de 2017,set de 2017,True,2017,2017
348,Trojan Technologies,out de 2016 – set de 2017,"Varginha e Região, Brasil",Trade Marketing,76,out de 2016,set de 2017,True,2016,2017
350,Trojan Technologies,mar de 2016 – set de 2017,São Paulo e Belo Horizonte,Key Account Manager,77,mar de 2016,set de 2017,True,2016,2017
354,Trojan Technologies,out de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Head of Product Design - UXP,78,out de 2016,set de 2017,True,2016,2017
359,Trojan Technologies,fev de 2017 – set de 2017,"Manaus e Região, Brasil",Lead Software Developer,79,fev de 2017,set de 2017,True,2017,2017
364,Trojan Technologies,out de 2016 – set de 2017,"Manaus e Região, Brasil",Software Test Developer II,80,out de 2016,set de 2017,True,2016,2017
369,Trojan Technologies,out de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Finance Director,81,out de 2016,set de 2017,True,2016,2017
374,Trojan Technologies,jul de 2017 – set de 2017,"Manaus e Região, Brasil",Desenvolvedor Jr,82,jul de 2017,set de 2017,True,2017,2017
379,Trojan Technologies,fev de 2017 – set de 2017,"Manaus e Região, Brasil",Desenvolvedor Junior,83,fev de 2017,set de 2017,True,2017,2017
382,Trojan Technologies,out de 2016 – set de 2017,Manaus,Desenvolvedor Pleno I,84,out de 2016,set de 2017,True,2016,2017
385,Trojan Technologies,abr de 2017 – set de 2017,"Manaus, Amazonas",iOS Developer,85,abr de 2017,set de 2017,True,2017,2017
389,Trojan Technologies,out de 2016 – set de 2017,"Manaus e Região, Brasil",Software Developer,86,out de 2016,set de 2017,True,2016,2017
394,Trojan Technologies,out de 2016 – set de 2017,Brazil,Desenvolvedora de Software,87,out de 2016,set de 2017,True,2016,2017
395,Trojan Technologies,out de 2016 – set de 2017,NaN,Software Developer,88,out de 2016,set de 2017,True,2016,2017
398,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Time de Expansão Local,89,mar de 2017,set de 2017,True,2017,2017
401,Trojan Technologies,mar de 2016 – set de 2017,"Belo Horizonte e Região, Brasil",Data Engineer BI and Data Analyst,90,mar de 2016,set de 2017,True,2016,2017
406,Trojan Technologies,jun de 2017 – set de 2017,"Belo Horizonte e Região, Brasil",Especialista em Marketing de Performance,91,jun de 2017,set de 2017,True,2017,2017
411,Trojan Technologies,ago de 2014 – set de 2017,NaN,Analista de Atendimento,92,ago de 2014,set de 2017,True,2014,2017
414,Trojan Technologies,mar de 2017 – set de 2017,"Belo Horizonte, Minas Gerais",Executivo de vendas,93,mar de 2017,set de 2017,True,2017,2017
418,Trojan Technologies,abr de 2017 – set de 2017,"São Paulo e Região, Brasil",Head Of Sales,94,abr de 2017,set de 2017,True,2017,2017
423,Trojan Technologies,ago de 2017 – set de 2017,"Belo Horizonte Area, Brazil",Head Of Strategy,95,ago de 2017,set de 2017,True,2017,2017
428,Trojan Technologies,jun de 2017 – set de 2017,NaN,Business Developer + Product Manager,96,jun de 2017,set de 2017,True,2017,2017
433,Trojan Technologies,mar de 2017 – set de 2017,"São Paulo e Região, Brasil",Executivo Comercial Senior,97,mar de 2017,set de 2017,True,2017,2017
438,Trojan Technologies,mai de 2017 – set de 2017,NaN,Inside Sales,98,mai de 2017,set de 2017,True,2017,2017
443,Trojan Technologies,2017 – set de 2017,"Rio de Janeiro Area, Brazil",Gerente Regional Rio de Janeiro,99,2017,set de 2017,True,2017,2017
448,Trojan Technologies,mar de 2017 – set de 2017,"São Paulo e Região, Brasil",Coordenador Comercial,100,mar de 2017,set de 2017,True,2017,2017
456,Trojan Technologies,fev de 2017 – set de 2017,"São Paulo e Região, Brasil",Gerente comercial Sao Paulo,101,fev de 2017,set de 2017,True,2017,2017
461,Trojan Technologies,fev de 2017 – set de 2017,"São Paulo e Região, Brasil",Executiva de Contas,102,fev de 2017,set de 2017,True,2017,2017
465,Trojan Technologies,2017 – set de 2017,"Brasília e Região, Brasil",Gerente Comercial e Operações Regional Centro-...,103,2017,set de 2017,True,2017,2017
470,Trojan Technologies,mar de 2017 – set de 2017,"São Paulo Area, Brazil",Sales Executive,104,mar de 2017,set de 2017,True,2017,2017
475,Trojan Technologies,jul de 2017 – set de 2017,"Manaus Area, Brazil",Software Architect,105,jul de 2017,set de 2017,True,2017,2017
480,Trojan Technologies,mar de 2017 – set de 2017,"São Paulo e Região, Brasil",Executivo de vendas,106,mar de 2017,set de 2017,True,2017,2017
485,Trojan Technologies,jun de 2017 – set de 2017,"São Paulo e Região, Brasil",Analista de marketing,107,jun de 2017,set de 2017,True,2017,2017
491,Trojan Technologies,mar de 2017 – set de 2017,"Porto Alegre, Rio Grande do Sul",Gerente Regional Sul,109,mar de 2017,set de 2017,True,2017,2017
496,Trojan Technologies,fev de 2017 – set de 2017,NaN,Software Developer,110,fev de 2017,set de 2017,True,2017,2017

## 05.4 Salvando Base Tratada

A base tratada será gravada no arquivo **experiencia_trabalho-tratado.csv**.

As informações consolidadas por perfil serão gravadas na base **perfil-experiencia,csv** contendo as colunas: **perfil_id**, **posicao_atual**, **data_admissao**, **departamento**, **tempo_empresa_meses**, **tempo_mercado_meses**, **qtd_empregos**.

In [ ]:
# Grava um csv tratado

### Navegação:
* [Voltar para a análise](00-analise-dos-dados.ipynb)