In [1]:
## Exemplo de sistema de recomendacao baseado em vizinho mais proximo

Execute o codigo e documente cada etapa. Devera ser gerado um relatorio final, que pode ser feito dentro do Jupyter Notebook mesmo, contendo

SyntaxError: ignored

In [2]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

In [0]:
dataFile='ratings.csv'
data=pd.read_csv(dataFile,sep=",",header=0,names=["userId","movieId","rating","timestamp"])

In [0]:
data.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [0]:
movieFile='movies.csv'
movies=pd.read_csv(movieFile,sep=",",header=0,names=["movieId","title","genres"])

In [0]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [0]:
def movieMeta(movieId):
    title = movies.at[movieId,"title"]
    genre = movies.at[movieId,"genres"]
    return title, genre
movieMeta(2)

('Grumpier Old Men (1995)', 'Comedy|Romance')

In [0]:
data = data[data["movieId"].isin(movies.index)]

In [0]:
def faveMovies(user,N):
    userRatings = data[data["userId"]==user]
    sortedRatings = pd.DataFrame.sort_values(userRatings,['rating'],ascending=[0])[:N] 
    sortedRatings["title"] = sortedRatings["movieId"].apply(movieMeta)
    return sortedRatings

In [0]:
faveMovies(1,10)

,userId,movieId,rating,timestamp,title
4,1,1172,4.0,1260759205,"(Gridlock'd (1997), Crime)"
13,1,2105,4.0,1260759139,"(Besieged (a.k.a. L' Assedio) (1998), Drama)"
12,1,1953,4.0,1260759191,"(At First Sight (1999), Drama)"
8,1,1339,3.5,1260759125,"(Red Corner (1997), Crime|Thriller)"
19,1,3671,3.0,1260759117,"(War of the Roses, The (1989), Comedy|Drama)"
1,1,1029,3.0,1260759179,"(Highlander (1986), Action|Adventure|Fantasy)"
2,1,1061,3.0,1260759182,"(Hype! (1996), Documentary)"
14,1,2150,3.0,1260759194,"(General's Daughter, The (1999), Crime|Drama|M..."
17,1,2455,2.5,1260759113,"(Pokémon: The First Movie (1998), Adventure|An..."
0,1,31,2.5,1260759144,"(Twelve Monkeys (a.k.a. 12 Monkeys) (1995), My..."

In [0]:
data.shape

(84739, 4)

In [0]:
usersPerMOVIE = data.movieId.value_counts()
usersPerMOVIE.head(10)

356     341
296     324
318     311
593     304
260     291
480     274
2571    259
1       247
527     244
589     237
Name: movieId, dtype: int64

In [0]:
usersPerMOVIE.shape

(5642,)

In [0]:
MOVIESsPerUser = data.userId.value_counts()

In [0]:
MOVIESsPerUser.shape

(671,)

In [0]:
data = data[data["movieId"].isin(usersPerMOVIE[usersPerMOVIE>10].index)]

In [0]:
data = data[data["userId"].isin(MOVIESsPerUser[MOVIESsPerUser>10].index)]

In [0]:
userItemRatingMatrix=pd.pivot_table(data, values='rating',
                                    index=['userId'], columns=['movieId'])

In [0]:
userItemRatingMatrix.head()

movieId,1,2,3,4,5,6,7,9,10,11,...,8957,8958,8961,8966,8970,8972,8981,8983,8984,8985
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [0]:
userItemRatingMatrix.shape

(666, 1759)

In [0]:
user1 = 1
user2 = 20

In [0]:
user1Ratings = userItemRatingMatrix.transpose()[user1]
user1Ratings.head(100)

movieId
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
9      NaN
10     NaN
11     NaN
12     NaN
14     NaN
15     NaN
16     NaN
17     NaN
18     NaN
19     NaN
20     NaN
21     NaN
22     NaN
23     NaN
24     NaN
25     NaN
28     NaN
29     NaN
31     2.5
32     NaN
34     NaN
35     NaN
36     NaN
      ...
125    NaN
135    NaN
140    NaN
141    NaN
144    NaN
145    NaN
147    NaN
150    NaN
151    NaN
153    NaN
154    NaN
156    NaN
158    NaN
160    NaN
161    NaN
162    NaN
163    NaN
164    NaN
165    NaN
168    NaN
170    NaN
172    NaN
173    NaN
175    NaN
176    NaN
177    NaN
180    NaN
181    NaN
185    NaN
186    NaN
Name: 1, Length: 100, dtype: float64

In [0]:
user2Ratings = userItemRatingMatrix.transpose()[user2]

In [0]:
from scipy.spatial.distance import hamming 
hamming(user1Ratings,user2Ratings)

1.0

In [0]:
import numpy as np
def distance(user1,user2):
        try:
            user1Ratings = userItemRatingMatrix.transpose()[user1]
            user2Ratings = userItemRatingMatrix.transpose()[user2]
            distance = hamming(user1Ratings,user2Ratings)
        except: 
            distance = np.NaN
        return distance

In [0]:
distance(6,5)

0.9994314951677089

In [0]:
user = 6
allUsers = pd.DataFrame(userItemRatingMatrix.index)
allUsers = allUsers[allUsers.userId!=user]
allUsers.head(10)

    userId
0        1
1        2
2        3
3        4
4        5
6        7
7        8
8        9
9       10
10      11

In [0]:
allUsers["distance"] = allUsers["userId"].apply(lambda x: distance(user,x))

In [0]:
allUsers.head()

   userId  distance
0       1  1.000000
1       2  1.000000
2       3  1.000000
3       4  1.000000
4       5  0.999431

In [0]:
K = 10
KnearestUsers = allUsers.sort_values(["distance"],ascending=True)["userId"][:K]

In [0]:
KnearestUsers

72      73
465    468
252    253
118    119
29      30
104    105
649    654
544    547
558    561
200    201
Name: userId, dtype: int64

In [0]:
def nearestNeighbors(user,K=10):
    allUsers = pd.DataFrame(userItemRatingMatrix.index)
    allUsers = allUsers[allUsers.userId!=user]
    allUsers["distance"] = allUsers["userId"].apply(lambda x: distance(user,x))
    KnearestUsers = allUsers.sort_values(["distance"],ascending=True)["userId"][:K]
    return KnearestUsers

In [0]:
KnearestUsers = nearestNeighbors(user)

In [0]:
KnearestUsers

72      73
465    468
252    253
118    119
29      30
104    105
649    654
544    547
558    561
200    201
Name: userId, dtype: int64

In [0]:
NNRatings = userItemRatingMatrix[userItemRatingMatrix.index.isin(KnearestUsers)]
NNRatings

movieId,1,2,3,4,5,6,7,9,10,11,...,8957,8958,8961,8966,8970,8972,8981,8983,8984,8985
userId,,,,,,,,,,,,,,,,,,,,,
30,4.0,2.0,NaN,NaN,NaN,4.0,NaN,NaN,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,5.0,2.5,NaN,NaN,NaN,4.5,NaN,NaN,3.0,NaN,...,4.0,NaN,3.0,NaN,NaN,3.0,NaN,NaN,2.5,NaN
105,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,3.5,3.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,2.0,3.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,...,NaN,5.0,5.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN
253,4.5,4.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
468,4.0,2.0,2.5,NaN,NaN,3.5,NaN,NaN,3.0,2.0,...,NaN,3.0,3.5,NaN,3.0,NaN,3.0,NaN,NaN,NaN
547,3.5,NaN,NaN,NaN,NaN,2.5,2.0,NaN,NaN,3.0,...,NaN,4.5,NaN,4.0,3.5,NaN,4.0,NaN,2.5,NaN
561,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,3.5,NaN,...,NaN,NaN,4.5,NaN,NaN,4.0,NaN,NaN,4.0,NaN
654,5.0,3.0,NaN,NaN,4.0,NaN,NaN,NaN,4.0,4.5,...,NaN,4.5,5.0,NaN,4.5,NaN,NaN,NaN,NaN,NaN

In [0]:
avgRating = NNRatings.apply(np.nanmean).dropna()
avgRating.head()

/home/puc/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4933: RuntimeWarning: Mean of empty slice
  labels=labels)

movieId
1    4.000000
2    2.785714
3    2.500000
5    4.000000
6    3.928571
dtype: float64

In [0]:
moviesAlreadyWatched = userItemRatingMatrix.transpose()[user].dropna().index
moviesAlreadyWatched

Int64Index([ 111,  158,  173,  293,  596,  903, 1204, 1250, 1259, 1276, 1285,
            1358, 1639, 1687, 1747, 1876, 1909, 2001, 2019, 2072, 2174, 2502,
            2528, 2529, 2571, 2657, 2692, 2723, 2761, 2890, 3052, 3114, 3300,
            3751, 4641, 4975, 5952, 7090, 7153, 7361, 8368, 8636, 8784, 8874],
           dtype='int64', name='movieId')

In [0]:
avgRating = avgRating[~avgRating.index.isin(moviesAlreadyWatched)]

In [0]:
N=3
topNMOVIEIDs = avgRating.sort_values(ascending=False).index[:N]

In [0]:
pd.Series(topNMOVIEIDs).apply(movieMeta)

0                                (Wilde (1997), Drama)
1    (Amazing Panda Adventure, The (1995), Adventur...
2    (Postman, The (1997), Action|Adventure|Drama|S...
Name: movieId, dtype: object

In [0]:
def topN(user,N=3):
    KnearestUsers = nearestNeighbors(user)
    NNRatings = userItemRatingMatrix[userItemRatingMatrix.index.isin(KnearestUsers)]
    avgRating = NNRatings.apply(np.nanmean).dropna()
    moviesAlreadyWatched = userItemRatingMatrix.transpose()[user].dropna().index
    avgRating = avgRating[~avgRating.index.isin(moviesAlreadyWatched)]
    ratingPredictedValue = avgRating.sort_values(ascending=False)
    #print(ratingPredictedValue.head(N))
    topNMOVIEIDs = avgRating.sort_values(ascending=False).index[:N]
    recommendation = pd.DataFrame(topNMOVIEIDs) 
    recommendation["title"] = recommendation["movieId"].apply(movieMeta)
    recommendation["Prediction"] = ratingPredictedValue.values[:N]
    return recommendation

In [0]:
faveMovies(3,10)

,userId,movieId,rating,timestamp,title
133,3,3949,5.0,1298863174,"(Sandlot, The (1993), Children|Comedy|Drama)"
113,3,1197,5.0,1298932770,"(Crash (1996), Drama|Thriller)"
101,3,318,5.0,1298862121,"(Crow, The (1994), Action|Crime|Fantasy|Thriller)"
103,3,356,5.0,1298862167,"(Mirage (1995), Action|Thriller)"
130,3,2959,5.0,1298862874,"(Bird on a Wire (1990), Action|Comedy|Romance)"
100,3,296,4.5,1298862418,"(Tom & Viv (1994), Drama)"
119,3,1721,4.5,1298923236,"(Return to Paradise (1998), Crime|Drama|Romanc..."
97,3,110,4.0,1298922049,"(Boomerang (1992), Comedy|Romance)"
129,3,2858,4.0,1298921825,"(Hidden, The (1987), Action|Horror|Sci-Fi)"
111,3,778,4.0,1298863157,"(Angel on My Shoulder (1946), Crime|Drama)"

In [0]:
topN(6,70)

/home/puc/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:4933: RuntimeWarning: Mean of empty slice
  labels=labels)

    movieId                                              title  Prediction
0      1946                              (Wilde (1997), Drama)    5.000000
1       125  (Amazing Panda Adventure, The (1995), Adventur...    5.000000
2      1361  (Postman, The (1997), Action|Adventure|Drama|S...    5.000000
3      3260      (Invisible Circus, The (2001), Drama|Romance)    5.000000
4       994   (Terminator, The (1984), Action|Sci-Fi|Thriller)    5.000000
5      1264                  (Air Bud (1997), Children|Comedy)    5.000000
6      1260     (George of the Jungle (1997), Children|Comedy)    5.000000
7       282         (Stargate (1994), Action|Adventure|Sci-Fi)    5.000000
8       262    (Outbreak (1995), Action|Drama|Sci-Fi|Thriller)    5.000000
9      2941  (Light Years (Gandahar) (1988), Adventure|Anim...    5.000000
10     1797                     (One True Thing (1998), Drama)    5.000000
11     1251     (Face/Off (1997), Action|Crime|Drama|Thriller)    5.000000
12      215            (Gordy (1995), Children|Comedy|Fantasy)    5.000000
13     1873    (Godzilla (Gojira) (1954), Drama|Horror|Sci-Fi)    5.000000
14      194                      (Castle Freak (1995), Horror)    5.000000
15      176             (Tie That Binds, The (1995), Thriller)    5.000000
16     3060  (Space Cowboys (2000), Action|Adventure|Comedy...    5.000000
17     4033      (Death to Smoochy (2002), Comedy|Crime|Drama)    5.000000
18     2357        (Man Facing Southeast (1986), Drama|Sci-Fi)    5.000000
19     1217            (Volcano (1997), Action|Drama|Thriller)    5.000000
20     2269                (Outside Providence (1999), Comedy)    5.000000
21     2303          (Sommersby (1993), Drama|Mystery|Romance)    4.833333
22     3022                    (Rocketship X-M (1950), Sci-Fi)    4.750000
23     7099                    (Igor (2008), Animation|Comedy)    4.750000
24     1147              (Whole Wide World, The (1996), Drama)    4.750000
25      920                       (Raw Deal (1948), Film-Noir)    4.750000
26      913                    (Hustler White (1996), Romance)    4.750000
27     3467         (Closet, The (Placard, Le) (2001), Comedy)    4.750000
28     3868                          (How High (2001), Comedy)    4.750000
29      647  (Hunchback of Notre Dame, The (1996), Animatio...    4.750000
..      ...                                                ...         ...
40      926         (Bloody Child, The (1996), Drama|Thriller)    4.500000
41      928         (Bad Moon (1996), Action|Adventure|Horror)    4.500000
42     2459               (Holiday Inn (1942), Comedy|Musical)    4.500000
43      904  (Abyss, The (1989), Action|Adventure|Sci-Fi|Th...    4.500000
44      921                          (T-Men (1947), Film-Noir)    4.500000
45     1280     (187 (One Eight Seven) (1997), Drama|Thriller)    4.500000
46      898                 (Funeral, The (1996), Crime|Drama)    4.500000
47     6773          (My Winnipeg (2007), Documentary|Fantasy)    4.500000
48     1218        (Children of the Revolution (1996), Comedy)    4.500000
49      741     (Gone with the Wind (1939), Drama|Romance|War)    4.500000
50     3037  (Pokémon the Movie 2000 (2000), Animation|Chil...    4.500000
51     3629                          (Loverboy (1989), Comedy)    4.500000
52      938      (Grifters, The (1990), Crime|Drama|Film-Noir)    4.500000
53     2929   (White Christmas (1954), Comedy|Musical|Romance)    4.500000
54      940                     (Shooter, The (1997), Western)    4.500000
55     1948                         (Affliction (1997), Drama)    4.500000
56     3724              (Hunter, The (1980), Action|Thriller)    4.500000
57     3952                     (Hart's War (2002), Drama|War)    4.500000
58     1103       (Jingle All the Way (1996), Children|Comedy)    4.500000
59     3741                 (Big Trouble (2002), Comedy|Crime)    4.500000
60     1096          (Albino Alligator (1996), Crime|Thriller)    4.500000
61     1255          (Wild America (1997), Adventure|Children)    4.500000
62     1256          (Simple Wish, A (1997), Children|Fantasy)    4.500000
63     2349            (Brief Encounter (1946), Drama|Romance)    4.500000
64     2952           (Running Man, The (1987), Action|Sci-Fi)    4.500000
65     2141  (Loss of Sexual Innocence, The (1999), Drama|F...    4.500000
66     2857                    (Defying Gravity (1997), Drama)    4.500000
67     1213                        (Hollow Reed (1996), Drama)    4.500000
68     2971                (American Pimp (1999), Documentary)    4.500000
69     2917     (Puppet Master (1989), Horror|Sci-Fi|Thriller)    4.500000

[70 rows x 3 columns]